name: 🎤Translation Request
description: Request a template for translating p5.js documentation
title: "[Translation]: "
labels: ["translation", "needs-template"]
body:
  - type: dropdown
    id: language
    attributes:
      label: Target Language
      description: Which language do you want to translate to?
      options:
        - es (Spanish)
        - zh-hans (Chinese)
        - fr (French)
        - hi (Hindi)
    validations:
      required: true
  - type: input
    id: page_path
    attributes:
      label: Page to Translate
      description: What's the URL path of the page you want to translate? (e.g., /reference/p5.Camera/move)
      placeholder: /reference/p5/function-name
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contributor Guidelines](link-to-your-guidelines)
      options:
        - label: I agree to follow the p5.js Contributor Guidelines
          required: true