name: "🎤 Translation"
description: Translation issue or new Language Support
title: "[Translation]: "
labels: ["Translation"]
assignees: []

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug or new language request
      description: Please provide a clear and concise description
      placeholder: Lets hear your thoughts 
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide steps to reproduce the behavior.
      placeholder: 1. Go to... 2. Click on... 3. See error...
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
  - type: dropdown
    id: willing-to-work
    attributes:
      label: Would you like to work on this issue?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: false
