name: Translation Request
description: Request a template for translating p5.js documentation
title: "[Translation]: "
labels: ["translation", "needs-template"]
body:
  - type: dropdown
    id: language_type
    attributes:
      label: Language Type
      description: Are you translating to an existing supported language or proposing a new language?
      options:
        - Existing supported language
        - Proposing a new language
    validations:
      required: true
  
  - type: dropdown
    id: existing_language
    attributes:
      label: Existing Language
      description: Which supported language do you want to translate to?
      options:
        - es (Spanish)
        - zh (Chinese)
        - fr (French)
        - ja (Japanese)
        - hi (Hindi)
      placeholder: Select a language
    validations:
      required: false

  - type: input
    id: new_language
    attributes:
      label: New Language Proposal
      description: If you selected "Proposing a new language", please provide the language code and name (e.g., "pt (Portuguese)", "de (German)")
      placeholder: language-code (Language Name)
    validations:
      required: false
  
  - type: input
    id: page_path
    attributes:
      label: Page to Translate
      description: What's the URL path of the page you want to translate? (e.g., /reference/p5.Camera/move)
      placeholder: /reference/p5/function-name
    validations:
      required: true
      
  - type: textarea
    id: new_language_info
    attributes:
      label: New Language Information (if applicable)
      description: If proposing a new language, please provide any relevant information like writing direction (RTL/LTR), special character considerations, etc.
      placeholder: Additional information about the language...
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contributor Guidelines](link-to-your-guidelines)
      options:
        - label: I agree to follow the p5.js Contributor Guidelines
          required: true