name: 🎤Translation Request
description: Request a template for translating p5.js documentation
title: "[Translation]: "
labels: ["translation", "needs-template"]
body:
  - type: dropdown
    id: language
    attributes:
      label: Target Language
      description: Which language do you want to translate to?
      options:
        - es (Spanish)
        - zh-hans (Chinese)
        - fr (French)
        - hi (Hindi)
        - None of above
        
  - type: textarea
    id: other_language
    attributes:
      label: Specify Other Language
      description: Please specify the target language if "None of above" is selected.
      placeholder: e.g., de (German)

  - type: input
    id: page_path
    attributes:
      label: Page to Translate
      description: What's the URL path of the page you want to translate? (e.g., /reference/p5.Camera/move)
      placeholder: /reference/p5/function-name


  - type: textarea
    id: extra_details
    attributes:
      label: Additional Details
      description: Please provide any extra context or information that might help with the translation.
      placeholder: e.g., specific instructions, context, or additional notes...

  - type: checkboxes
    id: ask_instructions
    attributes:
      label: Do you need Instructions on how and where to start?
      description: Check this box if you need instructions on how and where to start the translation process.
      options:
        - label: Yes, please include instructions
          required: false
