name: Add Translation Labels

on:
  issues:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4.2.2
        
      - name: Get supported languages
        id: supported-languages
        run: |
          languages=$(ls -d translations/*/ | sed 's|translations/||g' | sed 's|/||g' | grep -v 'en' | tr '\n' ' ')
          echo "SUPPORTED_LANGUAGES=$languages" >> $GITHUB_ENV

      - name: Add labels for supported languages
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const supportedLanguages = "${{ env.SUPPORTED_LANGUAGES }}".split(' ').filter(lang => lang);
            const labels = supportedLanguages.map(lang => `translation:${lang}`);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });